dist: bionic
language: python
python:
- '3.8'
before_install:
- openssl aes-256-cbc -K $encrypted_77e6e08a37ba_key -iv $encrypted_77e6e08a37ba_iv
  -in client-secret.json.enc -out client-secret.json -d
- openssl aes-256-cbc -K $encrypted_77e6e08a37ba_key -iv $encrypted_77e6e08a37ba_iv
  -in .env_prod.enc -out AppEngineTest/.env_prod -d
install:
- pip install -r requirements.txt
script:
- python manage.py test
deploy:
  provider: gae
  keyfile: client-secret.json
  project: career-track-project
  on:
    branch: master
