dist: bionic
language: python
python:
- '3.8'
before_install:
- openssl aes-256-cbc -K $encrypted_77e6e08a37ba_key -iv $encrypted_77e6e08a37ba_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
install:
- pip install -r requirements.txt
script:
- python manage.py test
deploy:
  provider: gae
  keyfile: client-secret.json
  project: career-track-project
  on:
    branch: master
